Update Build OpenWrt.yml

diff --git a/.github/workflows/Build OpenWrt.yml b/.github/workflows/Build OpenWrt.yml
--- a/.github/workflows/Build OpenWrt.yml
+++ b/.github/workflows/Build OpenWrt.yml
@@ -76,13 +76,6 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: Check if firmware directory exists
-      run: |
-        if [ ! -d "openwrt/bin/targets/*/*" ]; then
-          echo "Error: Directory openwrt/bin/targets/*/* does not exist."
-          exit 1
-        fi
-
     - name: Compile the firmware
       id: compile
       run: |
@@ -93,6 +86,13 @@ jobs:
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+    - name: Check if firmware directory exists
+      run: |
+        if [ ! -d "openwrt/bin/targets/*/*" ]; then
+          echo "Error: Directory openwrt/bin/targets/*/* does not exist."
+          exit 1
+        fi
 
     - name: Check space usage
       if: (!cancelled())
